export type AccountType = "main" | "side" | "savings";

export type TransactionType = "income" | "expense";

export type PeriodType = "day" | "week" | "month" | "year" | "custom";

export interface Account {
    id: string;
    name: string;
    type: AccountType;
    initialBalance: number;
    currentBalance: number;
    currency: string;
    color: string;
    icon: string;
    isArchived: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface Category {
    id: string;
    type: TransactionType;
    name: string;
    icon: string;
    isUserDefined: boolean;
}

export interface Transaction {
    id: string;
    accountId: string;
    type: TransactionType;
    amount: number;
    categoryId: string;
    customCategoryName: string | null;
    transactionName: string | null;
    note: string | null;
    date: string;
    createdAt: string;
    updatedAt: string;
    isAutoGenerated: boolean;
    recurringId: string | null;
    isTransfer: boolean;
    transferGroupId: string | null;
    linkedRuleId: string | null;
    parentTransactionId: string | null;
}

export interface UserSettings {
    id: string;
    language: string;
    currency: string;
    country: string;
    backupProvider: "none" | "google" | "icloud";
    autoBackupEnabled: boolean;
    autoBackupFrequency: "daily" | "weekly" | "monthly";
    lastSelectedAccountId: string | null;
    lastSelectedPeriodType: PeriodType;
    lastCustomPeriodFrom: string | null;
    lastCustomPeriodTo: string | null;
    isFirstLaunch: boolean;
}

export interface RecurringTransaction {
    id: string;
    accountId: string;
    type: TransactionType;
    amount: number;
    categoryId: string;
    customCategoryName: string | null;
    note: string | null;
    startDate: string;
    repeatInterval: "daily" | "weekly" | "monthly" | "yearly";
    repeatDay: number | null;
    endType: "never" | "endDate" | "occurrences";
    endDate: string | null;
    occurrences: number | null;
    timezone: string;
    isActive: boolean;
    lastGeneratedAt: string | null;
    processedOccurrences: number;
}

export interface TransferRule {
    id: string;
    sourceAccountId: string;
    targetAccountId: string;
    allocationType: "percentage" | "fixed";
    percentage: number | null;
    fixedAmount: number | null;
    noteTemplate: string | null;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface BackupMetadata {
    id: string;
    lastBackupAt: string | null;
    backupVersion: string;
}

export interface IncomeDistributionRule {
    id: string;
    accountId: string;
    name: string;
    description: string | null;
    percentage: number;
    categoryId: string;
    color: string;
    icon: string;
    isActive: boolean;
    linkedToSmartTransfer: boolean;
    order: number;
    createdAt: string;
    updatedAt: string;
}

export interface IncomeDistributionCompletion {
    id: string;
    incomeTransactionId: string;
    ruleId: string;
    distributionTransactionId: string | null;
    status: "pending" | "completed" | "skipped";
    createdAt: string;
    updatedAt: string;
}
