import { useState, useMemo } from "react";
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    TouchableOpacity,
    Alert,
} from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
    Settings,
    Check,
    X,
    ChevronRight,
    AlertCircle,
    TrendingUp,
    Calendar,
    Edit2,
} from "lucide-react-native";

import { useApp } from "../../context/AppContext";
import { hapticSelection, hapticSuccess } from "../../utils/haptics";
import { getCategoryIconComponent } from "../../constants/categoryIcons";
import type { CategoryIconName } from "../../constants/categoryIcons";
import type { Transaction, IncomeDistributionRule, IncomeDistributionCompletion } from "../../types";


export default function DistributionScreen() {
    const router = useRouter();
    const insets = useSafeAreaInsets();
    const {
        accounts,
        transactions,
        categories,
        incomeDistributionRules,
        incomeDistributionCompletions,
        addTransaction,
        saveIncomeDistributionCompletion,
    } = useApp();

    const [expandedIncomeId, setExpandedIncomeId] = useState<string | null>(null);

    const incomeTransactions = useMemo(() => {
        return transactions
            .filter((transaction) => transaction.type === "income" && !transaction.isTransfer)
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
            .slice(0, 20);
    }, [transactions]);

    const getRulesForIncome = (incomeTransaction: Transaction): IncomeDistributionRule[] => {
        return incomeDistributionRules.filter(
            (rule) => rule.isActive && rule.accountId === incomeTransaction.accountId
        );
    };

    const getCompletionStatus = (
        incomeTransactionId: string,
        ruleId: string
    ): IncomeDistributionCompletion | undefined => {
        return incomeDistributionCompletions.find(
            (completion) =>
                completion.incomeTransactionId === incomeTransactionId && completion.ruleId === ruleId
        );
    };

    const handleToggleIncome = (incomeId: string) => {
        hapticSelection();
        setExpandedIncomeId(expandedIncomeId === incomeId ? null : incomeId);
    };

    const handleMarkStatus = (
        incomeTransaction: Transaction,
        rule: IncomeDistributionRule,
        status: "completed" | "skipped"
    ) => {
        hapticSelection();

        const distributionAmount = Math.round((rule.percentage / 100) * incomeTransaction.amount * 100) / 100;

        if (status === "completed") {
            const sourceTransactionName = incomeTransaction.transactionName || incomeTransaction.customCategoryName || incomeTransaction.note || `Income (${new Date(incomeTransaction.date).toLocaleDateString()})`;

            const distributedTransaction = addTransaction(
                incomeTransaction.accountId,
                "expense",
                distributionAmount,
                rule.categoryId,
                incomeTransaction.date,
                `${rule.percentage}% from ${sourceTransactionName}`,
                null,
                {
                    isAutoGenerated: false,
                    linkedRuleId: rule.id,
                    parentTransactionId: incomeTransaction.id,
                    transactionName: rule.name,
                }
            );

            if (!distributedTransaction) {
                Alert.alert("Error", "Failed to create distribution transaction");
                return;
            }

            saveIncomeDistributionCompletion(
                incomeTransaction.id,
                rule.id,
                status,
                distributedTransaction.id
            );

            hapticSuccess();
        } else {
            saveIncomeDistributionCompletion(
                incomeTransaction.id,
                rule.id,
                status,
                null
            );
            hapticSuccess();
        }
    };

    const handleEditDistribution = (incomeTransactionId: string, ruleId: string) => {
        Alert.alert(
            "Edit Distribution",
            "Do you want to change the status of this distribution?",
            [
                {
                    text: "Cancel",
                    style: "cancel",
                },
                {
                    text: "Mark as Done",
                    onPress: () => {
                        const income = incomeTransactions.find((t) => t.id === incomeTransactionId);
                        const rule = incomeDistributionRules.find((r) => r.id === ruleId);
                        if (income && rule) {
                            handleMarkStatus(income, rule, "completed");
                        }
                    },
                },
                {
                    text: "Mark as Skipped",
                    style: "destructive",
                    onPress: () => {
                        const income = incomeTransactions.find((t) => t.id === incomeTransactionId);
                        const rule = incomeDistributionRules.find((r) => r.id === ruleId);
                        if (income && rule) {
                            handleMarkStatus(income, rule, "skipped");
                        }
                    },
                },
            ]
        );
    };

    return (
        <View style={[styles.container, { paddingTop: insets.top }]}>
            <View style={styles.header}>
                <View style={styles.headerContent}>
                    <TrendingUp color="#3B82F6" size={28} />
                    <Text style={styles.headerTitle}>Income Distribution</Text>
                </View>
                <TouchableOpacity
                    style={styles.settingsButton}
                    onPress={() => {
                        hapticSelection();
                        router.push("/income-distribution" as any);
                    }}
                    testID="open-distribution-settings"
                >
                    <Settings color="#6B7280" size={22} />
                </TouchableOpacity>
            </View>

            <ScrollView
                contentContainerStyle={[
                    styles.scrollContent,
                    { paddingBottom: insets.bottom + 24 },
                ]}
            >
                {incomeTransactions.length === 0 ? (
                    <View style={styles.emptyState}>
                        <AlertCircle color="#9CA3AF" size={48} />
                        <Text style={styles.emptyStateText}>No income transactions</Text>
                        <Text style={styles.emptyStateSubtext}>
                            Add income transactions to distribute funds
                        </Text>
                    </View>
                ) : (
                    incomeTransactions.map((income) => {
                        const rules = getRulesForIncome(income);
                        const account = accounts.find((acc) => acc.id === income.accountId);
                        const category = categories.find((cat) => cat.id === income.categoryId);
                        const isExpanded = expandedIncomeId === income.id;

                        if (rules.length === 0) {
                            return null;
                        }

                        const formattedDate = new Date(income.date).toLocaleDateString("en-US", {
                            month: "short",
                            day: "numeric",
                            year: "numeric",
                        });

                        const transactionName = income.transactionName || income.customCategoryName || income.note || category?.name || "Income";

                        return (
                            <View key={income.id} style={styles.incomeCard}>
                                <TouchableOpacity
                                    style={styles.incomeHeader}
                                    onPress={() => handleToggleIncome(income.id)}
                                    testID={`income-item-${income.id}`}
                                >
                                    <View style={styles.incomeHeaderLeft}>
                                        <View style={[styles.accountDot, { backgroundColor: account?.color || "#6B7280" }]} />
                                        <View style={styles.incomeHeaderText}>
                                            <Text style={styles.incomeCategoryName}>{transactionName}</Text>
                                            <View style={styles.incomeMetaRow}>
                                                <Calendar color="#9CA3AF" size={12} />
                                                <Text style={styles.incomeDate}>{formattedDate}</Text>
                                                {account ? (
                                                    <>
                                                        <Text style={styles.incomeMetaSeparator}>•</Text>
                                                        <Text style={styles.incomeAccount}>{account.name}</Text>
                                                    </>
                                                ) : null}
                                            </View>
                                        </View>
                                    </View>
                                    <View style={styles.incomeHeaderRight}>
                                        <Text style={styles.incomeAmount}>${income.amount.toFixed(2)}</Text>
                                        <ChevronRight
                                            color="#9CA3AF"
                                            size={20}
                                            style={{
                                                transform: [{ rotate: isExpanded ? "90deg" : "0deg" }],
                                            }}
                                        />
                                    </View>
                                </TouchableOpacity>

                                {isExpanded && rules.length > 0 ? (
                                    <View style={styles.rulesContainer}>
                                        {rules.map((rule) => {
                                            const completion = getCompletionStatus(income.id, rule.id);
                                            const distributionAmount = Math.round((rule.percentage / 100) * income.amount * 100) / 100;
                                            const RuleIcon = getCategoryIconComponent(rule.icon as CategoryIconName);
                                            const expenseCategory = categories.find((cat) => cat.id === rule.categoryId);

                                            const isLinkedToTransfer = rule.linkedToSmartTransfer;

                                            return (
                                                <View
                                                    key={rule.id}
                                                    style={[
                                                        styles.ruleItem,
                                                        completion?.status === "completed" && styles.ruleItemCompleted,
                                                        completion?.status === "skipped" && styles.ruleItemSkipped,
                                                    ]}
                                                >
                                                    <View style={styles.ruleItemLeft}>
                                                        <View
                                                            style={[
                                                                styles.ruleIconContainer,
                                                                { backgroundColor: rule.color + "20" },
                                                            ]}
                                                        >
                                                            <RuleIcon color={rule.color} size={20} />
                                                        </View>
                                                        <View style={styles.ruleItemInfo}>
                                                            <Text style={styles.ruleName}>{rule.name}</Text>
                                                            <Text style={styles.ruleCategory}>
                                                                {expenseCategory?.name || "Unknown"}
                                                            </Text>
                                                            <Text style={styles.ruleAmount}>
                                                                {rule.percentage}% = ${distributionAmount.toFixed(2)}
                                                            </Text>
                                                        </View>
                                                    </View>

                                                    {isLinkedToTransfer ? (
                                                        <View style={styles.linkedCheckBadge}>
                                                            <Check color="#10B981" size={24} />
                                                        </View>
                                                    ) : completion ? (
                                                        <View style={styles.completionRow}>
                                                            {completion.status === "completed" ? (
                                                                <View style={styles.statusCompleted}>
                                                                    <Check color="#10B981" size={20} />
                                                                </View>
                                                            ) : (
                                                                <View style={styles.statusSkipped}>
                                                                    <X color="#EF4444" size={20} />
                                                                </View>
                                                            )}
                                                            <TouchableOpacity
                                                                style={styles.editButton}
                                                                onPress={() => handleEditDistribution(income.id, rule.id)}
                                                                testID={`edit-distribution-${rule.id}`}
                                                            >
                                                                <Edit2 color="#6B7280" size={16} />
                                                            </TouchableOpacity>
                                                        </View>
                                                    ) : (
                                                        <View style={styles.ruleActions}>
                                                            <TouchableOpacity
                                                                style={[styles.ruleActionButton, styles.completeButton]}
                                                                onPress={() => handleMarkStatus(income, rule, "completed")}
                                                                testID={`mark-complete-${rule.id}`}
                                                            >
                                                                <Check color="#10B981" size={18} />
                                                                <Text style={styles.completeButtonText}>Done</Text>
                                                            </TouchableOpacity>
                                                            <TouchableOpacity
                                                                style={[styles.ruleActionButton, styles.skipButton]}
                                                                onPress={() => handleMarkStatus(income, rule, "skipped")}
                                                                testID={`mark-skip-${rule.id}`}
                                                            >
                                                                <X color="#EF4444" size={18} />
                                                                <Text style={styles.skipButtonText}>No</Text>
                                                            </TouchableOpacity>
                                                        </View>
                                                    )}
                                                </View>
                                            );
                                        })}
                                    </View>
                                ) : null}
                            </View>
                        );
                    })
                )}
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFF",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    headerContent: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: "700" as const,
        color: "#111827",
    },
    settingsButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#F3F4F6",
        alignItems: "center",
        justifyContent: "center",
    },
    scrollContent: {
        padding: 20,
        gap: 16,
    },
    emptyState: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 64,
        gap: 12,
    },
    emptyStateText: {
        fontSize: 18,
        fontWeight: "600" as const,
        color: "#6B7280",
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: "#9CA3AF",
        textAlign: "center" as const,
    },
    incomeCard: {
        backgroundColor: "#FFF",
        borderRadius: 16,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    incomeHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 16,
    },
    incomeHeaderLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flex: 1,
    },
    accountDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    incomeHeaderText: {
        flex: 1,
        gap: 4,
    },
    incomeCategoryName: {
        fontSize: 16,
        fontWeight: "600" as const,
        color: "#111827",
    },
    incomeMetaRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    incomeDate: {
        fontSize: 13,
        color: "#6B7280",
    },
    incomeMetaSeparator: {
        fontSize: 13,
        color: "#D1D5DB",
    },
    incomeAccount: {
        fontSize: 13,
        color: "#6B7280",
    },
    incomeHeaderRight: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    incomeAmount: {
        fontSize: 18,
        fontWeight: "700" as const,
        color: "#10B981",
    },
    rulesContainer: {
        paddingHorizontal: 16,
        paddingBottom: 16,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: "#F3F4F6",
    },
    ruleItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 12,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    ruleItemCompleted: {
        backgroundColor: "#ECFDF5",
        borderColor: "#10B981",
    },
    ruleItemSkipped: {
        backgroundColor: "#FEF2F2",
        borderColor: "#FCA5A5",
    },
    ruleItemLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flex: 1,
    },
    ruleIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
    },
    ruleItemInfo: {
        flex: 1,
        gap: 2,
    },
    ruleName: {
        fontSize: 15,
        fontWeight: "600" as const,
        color: "#111827",
    },
    ruleCategory: {
        fontSize: 12,
        color: "#9CA3AF",
    },
    ruleAmount: {
        fontSize: 13,
        color: "#6B7280",
        fontWeight: "500" as const,
    },
    linkedCheckBadge: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: "#D1FAE5",
        alignItems: "center",
        justifyContent: "center",
    },
    completionRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    statusCompleted: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#D1FAE5",
        alignItems: "center",
        justifyContent: "center",
    },
    statusSkipped: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#FEE2E2",
        alignItems: "center",
        justifyContent: "center",
    },
    editButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#F3F4F6",
        alignItems: "center",
        justifyContent: "center",
    },
    ruleActions: {
        flexDirection: "row",
        gap: 8,
    },
    ruleActionButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1,
    },
    completeButton: {
        backgroundColor: "#ECFDF5",
        borderColor: "#10B981",
    },
    completeButtonText: {
        fontSize: 13,
        fontWeight: "600" as const,
        color: "#10B981",
    },
    skipButton: {
        backgroundColor: "#FEF2F2",
        borderColor: "#EF4444",
    },
    skipButtonText: {
        fontSize: 13,
        fontWeight: "600" as const,
        color: "#EF4444",
    },
});
